### ISSUE TITLE
“Index out of range” with Roboto-Regular

### ISSUE THREAD

**Issue by madprog** [devongovett/fontkit#131]
Hello, I have an issue with two fonts that I have downloaded from Google Fonts.

The font URL is https://fonts.gstatic.com/s/roboto/v16/CWB0XYA8bzo0kSThX0UTuA.woff2, and comes from the CSS query with Chrome to https://fonts.googleapis.com/css?family=Roboto:400,400i,700,700i&subset=latin

```css
[…]
/* latin */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v16/CWB0XYA8bzo0kSThX0UTuA.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215;
}
[…]
```

To reproduce the problem, I run this piece of code with node (and encounter the same exception as in the browser):
```javascript
var PDFDocument = require('pdfkit');
var fs = require('fs');

var pdfFile = 'test.pdf';
var fontFile = 'CWB0XYA8bzo0kSThX0UTuA.woff2';
var doc = new PDFDocument({  bufferPages: true });
var pdfStream = fs.createWriteStream(pdfFile);
doc.pipe(pdfStream);

doc.fontSize(12)
   .font(fontFile)
   .text("This is a test: The quick brown fox jumps over the lazy dog.");

doc.end();
```

And, last but not least, here is the exception and its stack trace:
```
buffer.js:1180
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range   
    at checkInt (buffer.js:1180:11)                                
    at Buffer.writeUInt16BE (buffer.js:1247:5)                     
    at TTFSubset._addGlyph (/workspace/test/node_modules/fontkit/src/subset/TTFSubset.js:31:16)                                        
    at TTFSubset.encode (/workspace/test/node_modules/fontkit/src/subset/TTFSubset.js:73:12)                                           
    at /workspace/test/node_modules/fontkit/src/subset/Subset.js:30:12                                                                 
    at _combinedTickCallback (internal/process/next_tick.js:131:7) 
    at process._tickCallback (internal/process/next_tick.js:180:9) 
    at Function.Module.runMain (module.js:607:11)                  
    at startup (bootstrap_node.js:158:16)                          
    at bootstrap_node.js:575:3   
```

After a quick investigation, I remarked that at [src/subset/TTFSubset.js#L24](https://github.com/devongovett/fontkit/blob/master/src/subset/TTFSubset.js#L24), `nextOffset` is smaller than `curOffset`, which would mean that the offsets in `this.font.loca.offsets` are not sorted.

What can I do to fix this?
